### ISSUE TITLE
Gesture API proposal:  replace tap with touch

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#114]
I am bringing this up for two reasons:
1. I prefer touch over tap because the UIKit APIs refer to _touch_ and _touches_.  See the UIControlEvent API and UIGestureRecognizers.  I realize the UIAutomation JavaScript API uses `tap` through the docs.
2. tap is a Ruby Kernel method.  Some tools, like RubyMine, can't figure out that `tap` is defined in the Cucumber World.  I can already hear the protests that we shouldn't change our API to accommodate a third-party tool.  The reality is that many people use RubyMine and many people use RubyMine's Intentions feature that does static analysis of code.  All `tap` calls are being marked as having incorrect parameters.

I know that _tap_ is favored over _touch_ and I have little chance of influencing opinions.  What I hope is that we can document why we are choosing _tap_ over _touch_.

**Comment by TobiasRoikjer** [comment]
@krukow  ^

**Comment by jmoody** [comment]
![2015-05-29_14-18-57](https://cloud.githubusercontent.com/assets/466104/7882419/be890ae0-060d-11e5-989e-f32d1d78470f.png)

**Comment by jmoody** [comment]
Is there some way we can force RubyMine to pick up our implementation?

**Comment by krukow** [comment]
I want `tap`! Let's get in touch with the RubyMine folks.

**Comment by TobiasRoikjer** [comment]
@jmoody @krukow It's work noticing that this would only happen in the Cucumber steps, not in pages or modules. Further, it would work if Rubymine parsed the Cucumber `World` command.

**Comment by jmoody** [comment]
I think we need to understand @TeresaP's problem.

**Wrong number of arguments for 'tap' when upgrading to 17.0 (short-term solution inline)** [#961](https://github.com/calabash/calabash-ios/issues/961)

**Comment by TeresaP** [comment]
I'm happy to provide more info. What do you need from me?

**Comment by jmoody** [comment]
Contacting Teresa off channel.

**Comment by jmoody** [comment]
I paired with @svandeven - they are also having a problem with `tap`.

This is more evidence that overriding Kernel methods is not a good idea.  She also mentioned that she has paired with other users who have exactly this problem.

For what it is worth, `tap` has been removed from Calabash iOS in 0.19.0.

**Comment by jmoody** [comment]
ATTN @krukow @TobiasRoikjer

**Comment by TobiasRoikjer** [comment]
@jmoody We could also consider introducing a global object like `app.tap`. This will also help with autocompletion.
