### ISSUE TITLE
Default hooks generated by skeleton require iOS users to have patched Calabash with LifeCycle hooks

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#186]
Maybe I am wrong, but I think this is the case.

I can't investigate right now, but we can't lose track of this.

**Comment by TobiasRoikjer** [comment]
Sure.

**Comment by TobiasRoikjer** [comment]
@jmoody Do you have further comments on this? Is there a bug

**Comment by jmoody** [comment]
This might be a moot point if we can remove the iOS life cycle hooks.

What we don't want is to _require_ iOS users to implement the life cycle hooks.

**Comment by jmoody** [comment]
Closing because I think this will be covered in a different issue.
