### ISSUE TITLE
query("view marked:'does not exist'").first should not raise error

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#190]
Hey Tobias,

I think you are going to say that this is expected behavior.

I don't think this is a good behavior.  If the result of query is supposed to pose as an Array, I should be able to call `first` on the result and get back `nil`.

### Reproduce

1. query for an element on the screen that isn't there
2. ask for the first result

### Expected

> query("view marked:'does not exist'").first
=> nil

### Found

```
> query("UINavigationBar").first
IndexError: Query result is empty
        from /Users/moody/git/calabash/calabash/lib/calabash/query_result.rb:56:in `ensure_in_bounds'
        from /Users/moody/git/calabash/calabash/lib/calabash/query_result.rb:23:in `first'
        from (irb):5
        from /Users/moody/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
```

**Comment by jmoody** [comment]
Here is an example:

```ruby

        #  What I expected to work.
        navbar = _gesture_waiter.query('UINavigationBar').first
        if navbar
          points_from_top = points_from_top + navbar['frame']['height']
        end

        # What I had to do instead.
        result = _gesture_waiter.query('UINavigationBar')
        if !result.empty?
          navbar = result.first
          points_from_top = points_from_top + navbar['frame']['height']
        end
```

**Comment by jmoody** [comment]
@krukow This is expected behavior.

It is a subtle point and one that you should understand.

The goal is to replace this kind of error output:

```ruby
> query("returns no results").first['text']
NoMethodError: undefined method `[]' for nil:NilClass
```

with this error output:

```ruby
> query("returns no results").first['text']
IndexError: Query result is empty
```

**Comment by krukow** [comment]
Also requires a conversation @jmoody and @TobiasRoikjer -- my immediate preference is to return `nil`

**Comment by TobiasRoikjer** [comment]
@krukow Did you read Moodys last post on this? I would like us not to change Ruby default behaviour, but I think it is better to give a good error message, a lot of our users experience something similar.

We aren't *changing* anything in Ruby, as we have simply created an invariant of Array for Calabash that fails when accessing an element out of bounds instead of returning nil.
