### ISSUE TITLE
Is having the binaries in the features/prebuilt a good practice?

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#196]
See [samples/wordpress](https://github.com/calabash/calabash/tree/develop/samples/wordpress)

I am concerned that it will lead to the binary being uploaded 2x to the XTC - once because it was passed as an argument and again because it is in `features/`.

From a workflow perspective it is not great when using tools like vim and emacs - too many autocomplete matches (control-p on vim, c-x c-f on emacs).

It is also confusing because I believe the expectation is that the binaries will be _outside_ the features directory.  Walking up to the repo, I didn't know where the binaries where.  A README.md will sort that (I will write one now).

@krukow @olefriis Can you comment on the uploading 2x issue?

cc @TobiasRoikjer

**Comment by TobiasRoikjer** [comment]
@jmoody I agree on this actually. Good idea!
