### ISSUE TITLE
Can we remove the temporary .gitignores?

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#200]
```
# Temporary git ignores. Remove these when changing repos
android/test-server
playground/
# End of temporary git ignores
```

Playground doesn't need to be temporary does it? It can just be ignored?

**Comment by TobiasRoikjer** [comment]
@jmoody Yes for playground. No for the test-server :)

**Comment by jmoody** [comment]
Related to **Move the Android test server** [#1](https://github.com/calabash/calabash-android-server/issues/1)
