### ISSUE TITLE
Add with_page method 

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#250]

**Comment by TobiasRoikjer** [comment]
@jmoody Could you expand on this?

**Comment by jmoody** [comment]
Something like this:

```
page(WebViewApp::TabBar).with_active_page do |page|

end
```

or

```
with_page(WebViewApp::TabBar) do |page|

end
```

`with_active_page` only works because there is some logic in the page that can detect which tab we are looking at.  I don't think we should try to generalize this.

**Comment by TobiasRoikjer** [comment]
Closing this as this can be considered state-full, or at least scope-dependent. 

We want to be able to pinpoint the line that fails without having the investigate other parts of the code.
