### ISSUE TITLE
Run Calabash testrun project with cucumber 2.0.0

### ISSUE THREAD

**Issue by ericzered** [calabash/calabash#281]
Hello,
I've installed "calabash 2.0.0.pre3" because I saw in the feature that it will support cucumber 2.0.0 but to run my calabash cucumber test, I need the gem "calabash-cucumber".
So, because I can't find the pre-release for this gem, I still have :
"Unable to activate calabash-cucumber-0.14.3, because cucumber-2.0.0 conflicts with cucumber (~> 1.3.17) (Gem::ConflictError)"

How can I run a Calabash cucumber tests and keep cucumber 2.0.0 ? (I need this version on my machine) ?

My project start like this : 

@calabash_launcher = Calabash::Cucumber::Launcher.new
unless @calabash_launcher.calabash_no_launch?
@calabash_launcher.relaunch
@calabash_launcher.calabash_notify(self)

Thanks a lot

**Comment by jmoody** [comment]
If I understand correctly, you have installed Calabash 2.0 and Cucumber 2.0.

Now Calabash iOS 0.14.3 does not work because it requires Cucumber < 2.0.

You have two choices:

1. Use a Gemfile and bundler.  This is what we recommend.
2. Uninstall Cucumber 2.0

**Comment by ericzered** [comment]
Thanks for the answer,
I've got a gemfile for my project but it's "gem 'cucumber', '2.0.0'" in it because I need cucumber 2.0.0 for it.
So what I don't get it's : Calabash 2.0 support cucumber 2.0. But to run my calabash project, I need calabash-cucumber gem. And cucumber-calabah gem doesn't support cucumber 2.0.
So I'm stuck. I was hopping be able to run my tests with the pre-version.

**Comment by jmoody** [comment]
Calabash 2.0 and Calabash iOS 0.x are not compatible.  You cannot use them together.

In order to use Calabash 2.0 you will need to rewrite your steps and the files in your features/support directory.

As I asked before, please show us your Gemfile.

**Comment by ericzered** [comment]
I've got this in my gemfile 

gem 'cucumber', '2.0.0'

Because I need it.

In my env.rb I've put "require 'calabash-cucumber/cucumber'"
I've follow this step by step to build my app and run my cucumber tests to test it
http://docs.testmunk.com/en/latest/ios.html#install-calabash-gem

So I don't know what the difference between the "calabash" gem and "calabash-cucumber" gem.

**Comment by jmoody** [comment]
> Cucumber 2.0 - Because I need it.

What feature of cucumber 2.0 do you need?

> So I don't know what the difference between the "calabash" gem and "calabash-cucumber" gem.

* The calabash gem is also known as Calabash 2.0.
* The calabash-cucumber gem is also known as Calabash iOS or Calabash iOS 0.x.

Calabash 2.0 _replaces_ Calabash iOS 0.x and Calabash Android 0.x.  You cannot use them both together.

If you are TestMunk customer or client, I recommend contacting them for support.

### Sample Calabash iOS 0.x Gemfile

```
gem 'calabash-cucumber', '0.14.3'
```

### Sample Calabash 2.0  Gemfile

```
gem 'calabash', '2.0.0.pre3'
gem 'cucumber', '~> 2.0'
```

**Comment by ericzered** [comment]
Hello,
As example, I'm using "scenario.name" in cucumber 2.0 which return me the scenario name which I use for my screenshot name. All my project is based on this. And with cucumber 1.3 it doesn't work.
And all my team is using cucumber 2.0 for specific reason too.
if Calabash 2.0 replaces Calabash iOS, how can I launch a cucumber test ?
I'm not a testmunk customer, I just found this tutorial and it was perfectly working...
Thanks !

**Comment by jmoody** [comment]
> Cucumber 2.0

Great!  I did not know about that difference.

> if Calabash 2.0 replaces Calabash iOS, how can I launch a cucumber test ?

We haven't finished the documentation yet, but we have this example:

* https://github.com/calabash/calabash/tree/develop/cucumber/ios

In particular you should look at:

* https://github.com/calabash/calabash/blob/develop/cucumber/ios/features/support/hooks.rb

That example is not ideal because it has a bunch of extra stuff in the hooks.rb because it what we use to test the implementation.

It is important to understand two things:

1. The entire architecture has changed on Calabash 2.0:  the way you launch app and the way to open consoles is different.
2. Calabash 2.0 is _not_ backwards compatible with Calabash 0.x; you will have to update your scripts.

If you can host a tmate session, I would be happy to take a couple of moments to show you how things work.

**Comment by ericzered** [comment]
Thanks a lot, that's great ! I will try to update my code to adapt it to the new Calabash.
I'm new to Calabash (as you may guess it), my project is very simple, I hope it will be ok !
Have a nice day

**Comment by ericzered** [comment]
Hello again !
So I've tried to convert my script for the new Calabash but I'm completely lost. You're right, the hook is very confusing.
I'm able to clone the Calabash github and run the cucumber/ios after building the app.
But I didn't success to start my script.

My script is simple.
I've got this in my hooks : 

@calabash_launcher = Calabash::Cucumber::Launcher.new
		unless @calabash_launcher.calabash_no_launch?
			@calabash_launcher.relaunch
			@calabash_launcher.calabash_notify(self)
		 end
and this in my env.rb : 
APP_BUNDLE_PATH = File.expand_path("support/TeadsSDKDemo-cal.app")
DEVICE_TARGET="iPhone 5s (8.3 Simulator)"

And I really don't know how to launch the app now...
Thanks !

**Comment by tejasv02** [comment]
@ericzered  specifying calabash app path has changed in 2.0 
Sample command:
```
CAL_DEVICE_ID='xxx-xxx' CAL_DEBUG_CALLED_METHODS=1 CAL_DEBUG=1 CAL_APP=build/ios/xxx-cal.app bundle exec cucumber -p ios -v
CAL_DEVICE_ID='192.168.56.101:5555' CAL_DEBUG_CALLED_METHODS=1 CAL_DEBUG=1 CAL_APP=xx.apk bundle exec cucumber -p android -v
```

I havent managed to get calabash 2.0 running with my app , @jmoody can you please provide some inputs how to setup calabash 2.0 framework for ios App

Note: i tried above commands with calabash-ios gem present and also after uninstalling it.

here is my gem list 
```
Using CFPropertyList 2.3.1
Using awesome_print 1.6.1
Using builder 3.2.2
Using bundler 1.10.6
Using clipboard 1.0.6
Using edn 1.1.0
Using escape 0.0.4
Using geocoder 1.2.9
Using httpclient 2.6.0.1
Using json 1.8.3
Using retriable 2.0.2
Using thor 0.19.1
Using luffa 1.0.7
Using rubyzip 1.1.7
Using run_loop 1.4.1
Using calabash 1.9.9.pre3
Using coderay 1.1.0
Using multi_json 1.11.2
Using gherkin 2.12.2
Using cucumber-core 1.2.0
Using diff-lcs 1.2.5
Using multi_test 0.1.2
Installing cucumber 2.0.2
Using method_source 0.8.2
Using slop 3.6.0
Using pry 0.10.1
Using pry-nav 0.2.4
```

**Comment by ericzered** [comment]
Hello,
Thanks for the answer but I'm still blocked. I have a demo app, build with the last calabash framework, and gem calabash 2.0.0.pre4 installed. I want to start the ios simulator and my app from the calabash console.
So I'm launching "calabash console /Users/ericzered/Desktop/MyDemoApp-cal.app"
I have this : 
Running irb...

#             =>  Useful Methods  <=              #
>     ids => List all the visible ids.
> classes => List all the visible classes.
>    tree => The app's visible view hierarchy.
>    copy => Copy console commands to the Clipboard.
>   clear => Clear the console.
> verbose => Turn debug logging on.
>   quiet => Turn debug logging off.

Calabash 2.0.0.pre4 says: 'Can I get you a coffee?'
irb(main):001:0>

According to this doc, https://github.com/calabash/calabash/wiki/Calabash-2.0-and-0.x-Diff, now I'm doing "start_app" but I have : 
RuntimeError: App is not installed, you need to install it first.
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:673:in `expect_app_installed_on_simulator'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:372:in `expect_valid_simulator_state_for_starting'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:361:in `start_app_on_simulator'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:335:in `_start_app'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/device.rb:52:in `start_app'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/life_cycle.rb:41:in `start_app'
	from (irb):1
	from /Users/ericzered/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'

with old calabash, when I was running "start_test_server_in_background" in the console, ios simulator was opening and app too.
So how can I do that again ? 
Thanks !
