### ISSUE TITLE
Connection error to Calabash Server with DEVICE_TARGET cucumber

### ISSUE THREAD

**Issue by ericzered** [calabash/calabash#282]
I've build my iOS app and I can run it and control it with calabash.
On my Mac, when I run "cucumber", it launch an Iphone 5s Ios 8.3 Simulator, start the app and my actions are running, Calabash server connection are ok.
But when I run "DEVICE_TARGET="iPhone 5 s (8.3 Simulator)" cucumber" as example, I have an error :

  Unable to make connection to Calabash Server at http://localhost:37265/
  Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
   (RuntimeError)
  /Users/elerouge/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:806:in `rescue in ensure_connectivity'
  /Users/elerouge/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:771:in `ensure_connectivity'
  /Users/elerouge/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:642:in `relaunch'

So do you have any idea why it's ok with cucumber but not with a specific Simulator ? (even I choose a Iphone 5 s like the default one)
Thanks !

**Comment by jmoody** [comment]
This is a Calabash 0.x question, not a Calabash 2.0 question.

I believe you have typo in your variable:

```
$ DEVICE_TARGET="iPhone 5s (8.3 Simulator)" cucumber
```

If you are still having a problem in Calabash 0.14.3, please see this page for how to get help:  https://github.com/calabash/calabash-ios/wiki
