### ISSUE TITLE
Using .app on physical device

### ISSUE THREAD

**Issue by distortia** [calabash/calabash#284]
Hello,
I am trying to launch a physical device using a .app file. Calabash defaults to a simulator for .app and physical device for .ipa. Is there a way to support this or do I have to overwrite some methods?

Thanks

**Comment by jmoody** [comment]
.app cannot be installed on physical devices.

**Comment by distortia** [comment]
I am able to install from a .app using a third party installer, like ios-deploy.

**Comment by jmoody** [comment]
The third party installer must convert the .app to a .ipa.

You can use `xcrun PackageApplication` to create the .ipa from the .app.

http://stackoverflow.com/questions/5640776/xcode4-alternative-way-to-build-ipas

I am not sure what to say.  I've never heard of this use case. 

In any event, this is not a feature that I think Calabash will support.

**Comment by distortia** [comment]
Alright, thanks! I'll look into this.
