### ISSUE TITLE
Package not found in aapt output

### ISSUE THREAD

**Issue by distortia** [calabash/calabash#286]
Hey guys,
I am attempting to install and start the android app

This is the error message I am receiving:

ERROR: dump failed because assets could not be loaded

RuntimeError: 'package' not found in aapt output

Upon debugging, it appears to go through extract_identifier(android/application.rb) twice, the first time it comes back with the correct package, and the second time it comes back as nil. Causing this error. 

Note, that I am using Ruby Mine to kick off the scenarios and I currently have it working with iOS.
Thanks

**Comment by jmoody** [comment]
@TobiasRoikjer Any chance you can take a look?

**Comment by TobiasRoikjer** [comment]
@distortia Run using debug logging, then please paste everything in here

**Comment by distortia** [comment]
@TobiasRoikjer Here is everything man

/Users/staltn1/.rvm/rubies/ruby-2.2.0/bin/ruby -EUTF-8 -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/staltn1/.rvm/gems/ruby-2.2.0/bin/cucumber /Users/staltn1/RubymineProjects/redesign/features --format Teamcity::Cucumber::Formatter --expand -p none
Testing started at 1:31 PM ...
DEVICE: s5-22
BASE PARAMS:  SCREENSHOT_PATH=./output/ --no-color --format pretty --format junit --out hudson_report --format Calabash::Formatters::Html --out output/latest.html  --no-source browser=native platform=android ADB_DEVICE_ARG=51e2c998 TEST_SERVER_PORT=34800 ANDROID_HOME=/Users/staltn1/Web_Drivers APP_PATH=/Users/staltn1/Desktop/MyAppMobile-release.apk TEST_APP_PATH=/Users/staltn1/Desktop/test_servers/7763869c86a51658d78e8540daf663b4_2.0.0.pre4.apk CAL_APP=/Users/staltn1/Desktop/MyAppMobile-release.apk CAL_TEST_SERVER=/Users/staltn1/Desktop/test_servers -v --tags @Passing --tags ~@Expected-fail --tags ~@manual,~@Manual,~@Expected-fail --tags ~@broken --tags ~@fails
Code:
  * /Users/staltn1/RubymineProjects/redesign/features/support/env.rb
Setting Android SDK location to $ANDROID_HOME
Android SDK location set to '/Users/staltn1/Web_Drivers'
AAPT PATH:/Users/staltn1/Web_Drivers/build-tools/21.1.2/aapt
Set aapt path to '/Users/staltn1/Web_Drivers/build-tools/21.1.2/aapt'
Set zipalign path to '/Users/staltn1/Web_Drivers/build-tools/21.1.2/zipalign'
Set adb path to '/Users/staltn1/Web_Drivers/platform-tools/adb'
Set android jar path to '/Users/staltn1/Web_Drivers/platforms/android-21/android.jar'
Java SDK location set to ''
Found java on PATH
Set java path to '/usr/bin/java'
Found keytool on PATH
Set keytool path to '/usr/bin/keytool'
Found jarsigner on PATH
Set jarsigner path to '/usr/bin/jarsigner'
  * /Users/staltn1/RubymineProjects/redesign/features/support/data_merge.rb
  * /Users/staltn1/RubymineProjects/redesign/features/support/hooks.rb
  * /Users/staltn1/RubymineProjects/redesign/features/classes/page_helper.rb
  * /Users/staltn1/RubymineProjects/redesign/features/classes/validation_helper.rb
  * /Users/staltn1/RubymineProjects/redesign/features/pages/common_page.rb
  * /Users/staltn1/RubymineProjects/redesign/features/pages/homepage/home_page.rb
  * /Users/staltn1/RubymineProjects/redesign/features/paths/routes.rb
  * /Users/staltn1/RubymineProjects/redesign/features/step_definitions/steps.rb
  * /Users/staltn1/RubymineProjects/redesign/features/step_definitions/validation_steps.rb

Features:
  * /Users/staltn1/RubymineProjects/redesign/features/scenarios/test_concepts.feature
Parsing feature files took 0m0.004s

ADB Command: devices
ADB input: 
Ensuring /Users/staltn1/Desktop/MyAppMobile-release.apk is installed
ADB Command: -s, 51e2c998, shell
ADB input: ["pm list packages; echo \"__CAL_END__$?\"; exit 0"]
ADB Command: -s, 51e2c998, shell
ADB input: ["echo \"test\"; exit 0"]
Installing /Users/staltn1/Desktop/MyAppMobile-release.apk
ADB Command: -s, 51e2c998, push, /Users/staltn1/Desktop/MyAppMobile-release.apk, /data/local/tmp/MyAppMobile-release.apk
ADB input: 
ADB Command: -s, 51e2c998, shell
ADB input: ["pm install -r /data/local/tmp/MyAppMobile-release.apk; echo \"__CAL_END__$?\"; exit 0"]
ADB Command: -s, 51e2c998, shell
ADB input: ["pm list packages; echo \"__CAL_END__$?\"; exit 0"]
ADB Command: -s, 51e2c998, shell
ADB input: ["rm /data/local/tmp/MyAppMobile-release.apk; echo \"__CAL_END__$?\"; exit 0"]
Ensuring the test-server is installed as well
Ensuring /Users/staltn1/Desktop/test_servers is installed
ADB Command: -s, 51e2c998, shell
ADB input: ["pm list packages; echo \"__CAL_END__$?\"; exit 0"]
ERROR: dump failed because assets could not be loaded

RuntimeError: 'package' not found in aapt output
/Users/staltn1/.rvm/gems/ruby-2.2.0/gems/calabash-2.0.0.pre4/lib/calabash/android/application.rb:43:in `extract_identifier'
/Users/staltn1/.rvm/gems/ruby-2.2.0/gems/calabash-2.0.0.pre4/lib/calabash/application.rb:76:in `identifier'
/Users/staltn1/.rvm/gems/ruby-2.2.0/gems/calabash-2.0.0.pre4/lib/calabash/android/device.rb:719:in `_ensure_app_installed'
/Users/staltn1/.rvm/gems/ruby-2.2.0/gems/calabash-2.0.0.pre4/lib/calabash/device.rb:80:in `ensure_app_installed'
/Users/staltn1/.rvm/gems/ruby-2.2.0/gems/calabash-2.0.0.pre4/lib/calabash/android/device.rb:736:in `_ensure_app_installed'
/Users/staltn1/.rvm/gems/ruby-2.2.0/gems/calabash-2.0.0.pre4/lib/calabash/device.rb:80:in `ensure_app_installed'
/Users/staltn1/.rvm/gems/ruby-2.2.0/gems/calabash-2.0.0.pre4/lib/calabash/life_cycle.rb:93:in `ensure_app_installed'
/Users/staltn1/.rvm/gems/ruby-2.2.0/gems/calabash-webdriver-2.0.0.pre4/lib/calabash-webdriver/android.rb:25:in `for'
/Users/staltn1/.rvm/gems/ruby-2.2.0@global/gems/watir-launcher-1.0.5.pre/lib/watir-launcher/launcher.rb:21:in `launch_browser'
/Users/staltn1/RubymineProjects/redesign/features/support/hooks.rb:17:in `Before'

RuntimeError: Unable to pick a platform for the provided browser or element: nil.
nil was passed to the PageObject constructor instead of a valid browser or element object.
./features/step_definitions/steps.rb:4:in `/^I am a MyApp app user$/'
./features/scenarios/test_concepts.feature:4:in `Given I am a MyApp app user'

Skipped step
Skipped step
Skipped step1 scenario (1 failed)
4 steps (1 failed, 3 skipped)
0m18.554s

Process finished with exit code 1

**Comment by distortia** [comment]
Hey guys, just an update. I am closing the issue. I believe the issue was on my end, having to do with my test server.
