### ISSUE TITLE
using .ipa instead .app or iOS testing ?

### ISSUE THREAD

**Issue by ericzered** [calabash/calabash#292]
Hello,
I'm using Calabash 2 to test my app on iOS simulator, but I have a question : 
Can I test from an .ipa ?
Because my team is building me an .ipa file (which contains the .app) and for the process it will be wonderful if I can take this .ipa on my auto test and start Calabash from it.
Thanks !

**Comment by jmoody** [comment]
Use:

```
$ bundle exec calabash console /path/to/Your.ipa
$ bundle exec calabash run /path/to/Your.ipa
```

**Comment by ericzered** [comment]
Thanks a lot !
