### ISSUE TITLE
Install app on iOS 9.1 Simulator

### ISSUE THREAD

**Issue by ericzered** [calabash/calabash#293]
Hello,
I have my app and I can install it on iOS 8.1 Simulator to start and test it with Calabash 2
But when I try to install it on iOS 9.1, I can't, I have a freeze in the console, no error are display, jsut a freeze.

ericzered$ CAL_DEVICE_ID="iPhone 6 (9.1)" calabash console /Users/ericzered/Documents/Builds/test/MyAppDemo-cal.app
Running irb...

 =>  Useful Methods  <=
>     ids => List all the visible ids.
> classes => List all the visible classes.
>    tree => The app's visible view hierarchy.
>    copy => Copy console commands to the Clipboard.
>   clear => Clear the console.
> verbose => Turn debug logging on.
>   quiet => Turn debug logging off.

Calabash 2.0.0.pre4 says: 'Remember to breathe.'
irb(main):001:0> install_app

(and it's a freeze, I have to kill it)
Is iOS 9 supported by Calabash 2 ?
Thanks

**Comment by jmoody** [comment]
It does not support Xcode 7.  Which is a drag.

Too many fires on the Calabash 0.x side.

I have a local branch which fixes the problem, but I it is not pushed yet.

**Comment by ericzered** [comment]
Thanks for the info, I will use it only for ios 8.1 now.
Have a nice day
