### ISSUE TITLE
HTTPClient::ReceiveTimeoutError after installing Charles Root certificate on iOS Simulator

### ISSUE THREAD

**Issue by ericzered** [calabash/calabash#294]
Hello (again),
I test my app with Calabash 2.0, it was ok to install, launch and test it manually on iOS Simulator
But because I wanted to see https requests with Charles, I've installed "Charles root certificate on IOS simulator" in the SSL proxying part in Charles.
So now I can see my https traces but when I launch my app from Calabash I have HTTPClient::ReceiveTimeoutError.
My internet is ok (Chrome, Skype...), my app connections are ok, but I don't know why now I can't start my app from Calabash.

My error :
irb(main):001:0> install_app
true
irb(main):002:0> start_app
HTTPClient::ReceiveTimeoutError: execution expired
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:791:in `gets'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:791:in `block in parse_header'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:787:in `parse_header'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:770:in `read_header'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:546:in `get_header'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient.rb:1279:in `do_get_header'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient.rb:1226:in `do_get_block'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient.rb:1006:in `block in do_request'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient.rb:1114:in `protect_keep_alive_disconnected'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient.rb:1001:in `do_request'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient.rb:843:in `request'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/httpclient-2.7.0.1/lib/httpclient.rb:724:in `get'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/http/retriable_client.rb:134:in `block in request'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/http/retriable_client.rb:120:in `times'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/http/retriable_client.rb:120:in `request'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/http/retriable_client.rb:84:in `get'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:143:in `test_server_responding?'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/device.rb:120:in `block (2 levels) in ensure_test_server_ready'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/device.rb:119:in `loop'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/device.rb:119:in `block in ensure_test_server_ready'
	from /Users/ericzered/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /Users/ericzered/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /Users/ericzered/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/device.rb:118:in `ensure_test_server_ready'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:402:in `wait_for_server_to_start'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:364:in `start_app_on_simulator'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/ios/device/device_implementation.rb:335:in `_start_app'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/device.rb:52:in `start_app'
	from /Users/ericzered/.rvm/gems/ruby-2.2.1/gems/calabash-2.0.0.pre4/lib/calabash/life_cycle.rb:41:in `start_app'
	from (irb):2
	from /Users/ericzered/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'irb(maiirbirb(irb(main):0irb(main):003:irb(iiirirb(irb(mirb(iiirb(irb(mairbiiiirbirb(i

Thanks !

**Comment by ericzered** [comment]
I notice this too : 
On a fresh new ios Simulator (without Charles Root Certificate installed), when Charles is OFF, I can't start my app with calabash, I have a timeout. But the https connections on my app are ok, I can see the answers.
And when Charles is ON, Calabash connection is ok, I can control my app. But the https connections inside my app failed...
And when I install Charles certificate on my ios simulator, when Charles is open, https connections are ok, but Calabash give me now the timeOut...
So strange that I can't have both Calabash and https in app connections...

**Comment by ericzered** [comment]
Hello,
Still blocked with this. I see that when I check "Enable SSL Proxying" on Charles, Calabash connection is ok but my https in my app are not (so my app is useless).
And when I uncheck it, it's the total opposite...

**Comment by jmoody** [comment]
I don't know what Charles is.

Have you tried setting the device endpoint to https:

```
DEVICE_ENDPOINT=https://localhost:37265
```

I doubt this will work, but it is worth a try.

**Comment by ericzered** [comment]
Hello,
Thanks, I will try.
Charles is like Fiddler for Mac. It's used to see http and https traffic.
And right now, only way to have Calabash working is to have Charles open and "Enable SSL Proxying" checked. Without Charles, I have the Calabash Timeout, so strange...

**Comment by ericzered** [comment]
I've tested DEVICE_ENDPOINT=https://localhost:37265 and no change :(

**Comment by ericzered** [comment]
When I build my app in Xcode I see in the console : 
2015-11-24 13:34:33.246 DEBUG CalabashServer:222 | Creating the server: <LPHTTPServer: 0x7a6614b0>
2015-11-24 13:34:33.247 DEBUG CalabashServer:223 | Calabash iOS server version: CALABASH VERSION: 0.16.4
2015-11-24 13:34:33.247 DEBUG CalabashServer:226 | App Base SDK: iphonesimulator9.1
2015-11-24 13:34:33.248 DEBUG CalabashServer:254 | IPHONE_SIMULATOR_ROOT: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.3.simruntime/Contents/Resources/RuntimeRoot

Is that ok ?
Thanks

**Comment by LiohAu** [comment]
Given that Charles is an HTTP Proxy, you probably have a networking configuration issue (not related to calabash) that Charles solves unintentionally by acting as a proxy.

**Comment by jmoody** [comment]
@ericzered Please use GitHub formatting in your issues.

> 0.16.4

There is no 2.0 server; the 0.16.4 server is the correct version.
