### ISSUE TITLE
Calabash.framework download from Calabash 2.0

### ISSUE THREAD

**Issue by mvemjsun** [calabash/calabash#296]
Hi,

I was trying to download the `calabash.framework`  using calabash 2.0, not sure if this feature  is yet available  similar to the `calabash-ios download` command that we use for existing calabash-cucumber gem.

If this is not available can I continue to use the `calabash.framework` that has been downloaded with calabash-cucumber gem 0.16.3 and use this to test with calabash 2.0.

**Comment by distortia** [comment]
The list of commands ported from the individual gems are here https://github.com/calabash/calabash/issues/26. Ios setup and download are not checked off yet. I'd stick to calabash ios commands.

**Comment by jmoody** [comment]
@distortia is correct.  We are not sure how we are going to distribute libraries for Calabash 2.0.  They might be embedded, as they are in Calabash 0.x, or we might distribute them over http.

**Comment by mvemjsun** [comment]
@jmoody @distortia Thank you both, so I should be able to use the calabash.framework downloaded with say calabash-cucumber gem 0.16.2 with calabash 2.0.0.pre4 and an app linked with this framework.

**Comment by jmoody** [comment]
I would recommend 0.16.4.

Spoiler alert:  I am cutting the 0.17.0 release today.
