### ISSUE TITLE
Other Linker Flags not present in Xcode project

### ISSUE THREAD

**Issue by georgeedwards** [calabash/calabash#312]
I am trying to build some tests for the Xamarin Test Cloud for a non-Xamarin mobile app. I have followed the [guide](https://developer.xamarin.com/guides/testcloud/calabash/quickstarts/xcode/linking-the-calabash-framework/), but have got stuck on the _Linking the Calabash Framework_ step. My project doesn't seem to have any "Other linker Flags" setting, you can see this in the images below.

I am using XCode: **v7.3**
calabash-ios:       **0.19.2**
calabash-android:   **0.7.3**
xamarin-test-cloud: **2.0.0**

[![enter image description here](http://i.stack.imgur.com/bOpwB.png)](http://i.stack.imgur.com/bOpwB.png)

[![enter image description here](http://i.stack.imgur.com/mgi7m.png)](http://i.stack.imgur.com/mgi7m.png)

I have tried adding the string:

> -ObjC -force_load "$(SOURCE_ROOT)/calabash.framework/calabash" -framework CFNetwork

to the `Linking>Runpath Search Paths>Debug` setting as shown in the top image, however, this doesn't make the calabash server run with the application.

**Comment by jmoody** [comment]
Select "All" vs. Combined and search for Linker
