### ISSUE TITLE
Screenshot.obtain_screenshot_path! should respect 'SCREENSHOT_DIRECTORY'

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#67]
If the users says, "Use this directory for screenshots", don't insert `test_run_*`.

### Reproduce

```
$ be irb
Calabash 2.0.0.pre1 says: 'I'm gonna take this to 11.'
> ENV['CAL_SCREENSHOT_DIR']='/tmp/screenshots'
"/tmp/screenshots"
> Calabash::Screenshot.obtain_screenshot_path!
"screenshots/test_run_26/screenshot_1.png"
> 
```

### Expected

```
> Calabash::Screenshot.obtain_screenshot_path!
"screenshots/screenshot_1.png"
```

**Comment by jmoody** [comment]
@TobiasRoikjer What do you think?

**Comment by TobiasRoikjer** [comment]
@jmoody I don't think this is a good approach, we should rather have the user specify both. As the ENV will stay constant, the screenshots would be overwritten

**Comment by TobiasRoikjer** [comment]
Also, Calabash not using the ENV variable after being started is expected behaviour. The ENV used is the one supplied to Calabash, e.g. CAL_SCREENSHOT_DIR=xxx be irb.

**Comment by jmoody** [comment]
As a first run experience, it is not good.  I expected this work.  I asked calabash to put my screenshots somewhere and it didn't.
> the screenshots would be overwritten

So?  Is this really a problem?  Who is consuming these screenshots?  Mostly it is formatters...

> Also, Calabash not using the ENV variable after being started is expected behaviour. The ENV used is the one supplied to Calabash, e.g. CAL_SCREENSHOT_DIR=xxx be irb.

I should be able to control the environment through ENV without surprises.

Why don't we remove this intermediate directory all together?

**Comment by jmoody** [comment]
RESOLVED: Update the Screenshot docs to explain the behavior of the subdirectory.

**Comment by jmoody** [comment]
- [ ] Update docs
- [ ] Present this for feedback during demo

**Comment by jmoody** [comment]
Outdated!  Closing.
