### ISSUE TITLE
ideviceinstaller hooks in Calabash device

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#68]
ATTN @krukow @TobiasRoikjer 

My plan is to implement hooks for ideviceinstaller.  If the ideviceinstaller _command-line application_ is available, then we'll use it.  If it is not, we'll raise an error.

Here are my various attempts at an API.

* https://github.com/calabash/luffa/blob/develop/lib/luffa/ios/ideviceinstaller.rb
* https://github.com/jmoody/briar/blob/develop/bin/briar_ideviceinstaller.rb

Each has their own peculiar problems.  The luffa implementation is the 2nd pass.

@kamstrup mentioned this: https://github.com/blueboxsecurity/idevice

It is LGPL, which I think makes it unsuitable for us.

The long-term plan to provide instructions on how to implement hooks for other third-party installers.

**Comment by jmoody** [comment]
@krukow 

Unless you want these hooks in Calabash, we are going to provide an `install_on_device` method and instructions on how to override this method.

**Comment by krukow** [comment]
@jmoody I'm not sure what you're asking me to do here? why are they hooks? Are they not just regular methods - and if not in Calabash, then where are they?

**Comment by jmoody** [comment]
RESOLVED:  Device `install_app_on_device` will be abstract.
