### ISSUE TITLE
Does Calabash:IOS::Device need to implement port forward

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#76]
Hey Tobias,

What is the purpose of the Device#port_method?

Can we move this to Calabash::Android::Device?

**Comment by TobiasRoikjer** [comment]
@jmoody No. I guess the same concept is not needed for iOS. I'll make a PR to move this method

**Comment by TobiasRoikjer** [comment]
https://github.com/calabash/calabash/pull/81
