### ISSUE TITLE
Is it possible to say "install the app" and "clear the app" data?

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#77]
Hey Tobias,

I am asking because in the case of ideviceinstaller, the way you clear the app data is by re-installing.  Obviously, we want to avoid uninstalling + installing more than once.

**Comment by TobiasRoikjer** [comment]
installing the apk will reset the data - so
```ruby
install_app
clear_app_data
```
and
```ruby
install_app
```
Should be identical.
Does this answer your question?

**Comment by jmoody** [comment]
Installing and clearing app data are mutually exclusive.
